# Generated by Django 3.2 on 2021-04-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('resumo', models.TextField()),
                ('anoLancamento', models.IntegerField()),
                ('duracao', models.IntegerField()),
                ('genero', models.CharField(max_length=15)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
