# Generated by Django 3.2 on 2021-04-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('sobrenome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(max_length=9, unique=True)),
                ('dataNasc', models.DateField()),
                ('endereco', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=60, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('dataCadastro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
