# Generated by Django 3.2 on 2021-04-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=60)),
                ('complemento', models.CharField(blank=True, max_length=60)),
                ('cidade', models.CharField(max_length=60)),
                ('cep', models.CharField(max_length=9)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
    ]
